### ISSUE TITLE
Further documentation / examples to assist in troubleshooting

### ISSUE THREAD

**Issue by sonoflee** [Hestabit/craft-ajaxinate#11]
Hello, I'm just testing out the plugin and although I think I have followed all of your instructions I am still having trouble getting it to work - I keep getting "No more data found".  

Would it be possible to share a complete basic template (maybe using the Happy Lager site) that shows a working version after you've enabled things in Settings?

**Comment by insaurabh** [comment]
Hello @sonoflee , thanks for writing in.
Let me look into it and we'll get back to you after setting up a basic template.

**Comment by insaurabh** [comment]
@sonoflee  

We have done the basic settings. To perform the same setting you just need to modify the following file.

**File Path** : `<root>/templates/news/index.twig`

For complete changes see this gist : https://gist.github.com/insaurabh/1a00e4c4298c8f3ec9e2766be2d29366


Backend Settings.

![Craft-ajax](https://user-images.githubusercontent.com/26545067/68777075-215ebe00-0657-11ea-946e-6ea7b88cd4e0.gif)

File Changes:
![Crraft-ajax-settings](https://user-images.githubusercontent.com/26545067/68777287-6d116780-0657-11ea-9175-f75fe81065f7.gif)

Fronted with these settings.

![craft-ajaxinate-frontend](https://user-images.githubusercontent.com/26545067/68777477-b9f53e00-0657-11ea-8fba-a27a0a60cb64.gif)


Please let me know if that works.

**Comment by sonoflee** [comment]
These examples helped me get up and running. Thank you for taking the time!

**Comment by insaurabh** [comment]
Perfect! Glad we were able to help you out. :)
