### ISSUE TITLE
How to set the radio button in the filter

### ISSUE THREAD

**Issue by thefubon** [Hestabit/craft-ajaxinate#13]
How to set the radio button in the filter?

**Comment by insaurabh** [comment]
Hi, @thefubon 

Can you please share more about the issue or plugin settings?

You have two ways to pass the field handle.

```twig
{{ craft.craftAjaxinate.render({
    ....
      extraFilters: ['featuredEntry', 'price'],
   ....
      sortingFilters:{
        'date': 'eventDate',
        'price': 'price',
      },  
    }) }}
```

**Comment by thefubon** [comment]
Now everything works for me through the checkbox and I need a radio button. Since there is no support for selecting multiple sections in the filter, only a switch. That is why checkboxes are not a bit relevant.

**Comment by thefubon** [comment]
And it is possible to make categories in the category file.twig and when opening the page, and could display a certain category? For example when all posts I have are displayed all. But if I do not switch through the filter and go to the category page and only those that are in this category are displayed?

**Comment by insaurabh** [comment]
Hello @thefubon ,
This plugin doesn't change the field type. The type you defined in the backend will be used in the frontend. 

So if you need a checkbox filed for the filter,  just create a filed with that type only and pass in the plugin

```twig
{{ craft.craftAjaxinate.render({
``` 

You can share your plugin settings code that you are using in the template.

**Comment by thefubon** [comment]
```# Кнопка загрузить еще #}
	{{ craft.craftAjaxinate.render({
		containerClass: '.ajaxLoaderPost',
		template: 'news/_ajaxEntries',
		offset: 24,
		limit: 24,
		initLoad: true,
		section: ['games'],
		scrollActive: true,
		pagesToLoad: 2,
                bottomOffset: 300,

		noMoreDataMsg: 'No more data found.'|t,

		sortingFilters:{
			'date': 'eventDate',
		},

		extraFilters: ['games_category'],
		catGroup: ['games_category', 'games_date'],
		catGroupLimit: 100,
		tagGroup: ['newsTags'],

		query:{
                   'title':':notempty:',
               },

		selectClass: 'uk-select',
		optionClass: 'uk-option',

		ulClass: 'uk-list uk-list-divider',
		liClass: '',

		catWrapperClass: 'uk-margin uk-padding-small uk-background-default uk-border-rounded',
		checkFieldDiv: 'uk-background-default uk-padding-small uk-background-default uk-border-rounded',
		sortingWrapperClass: 'uk-margin uk-padding-small uk-background-default uk-border-rounded',

		nFirstName: 'Новички вперед',
		oFirstName: 'Старейший первый.',
		dSortName: 'Сортировка по умолчанию',

		resetBtnState: 1,
		resetWrapperClass: 'uk-padding-small uk-background-default uk-border-rounded',
	}) }}
```

**Comment by insaurabh** [comment]
@thefubon 

All settings appears to be correct.

Currently, this plugin doesn't change any field type. If you want to show a radio button please create a field of type radio in the backend.

**Comment by thefubon** [comment]
I tried it failed. Tell me exactly how to do this?

**Comment by insaurabh** [comment]
@thefubon,

Which field you want as a radio button in frontend and what is the type of that field in the backend?

**Comment by thefubon** [comment]
external need radio

**Comment by insaurabh** [comment]
> external need radio

I didn't understand what you are saying.

>This plugin currently don't change the field type.

**Comment by insaurabh** [comment]
Hello @thefubon ,

Are you still facing any issues? You can reopen this issue at any time.

Thank You.
