### ISSUE TITLE
[Craft-ajaxinate] :  Request failed: error

### ISSUE THREAD

**Issue by ryanjohnsonnc** [Hestabit/craft-ajaxinate#14]
I am scratching my head on this one. Yesterday, I set up the plugin to work per the documentation and was successfully retrieving the request data via ajax. 
Today I sat back down with my codebase and now I am getting an error in the console that states: [Craft-ajaxinate] :  Request failed: error, so the server is throwing a 500 error. 

Here is the code for my landing page
```
{% import "/_macros" as macros %}
{% set section = 'gallery' %}
{% extends "_layouts/main" %}

{% block content %}
  {# for craftAjaxinate plugin #}
  {% set csrfToken = {
    csrfTokenName: craft.app.config.general.csrfTokenName,
    csrfTokenValue: craft.app.request.csrfToken,
  } %}
  {% js %}
    window.Craft = {{ csrfToken | json_encode | raw }};
  {% endjs %}


  {% include '_partials/hero' with {
      headline: entry.headline,
      subheadline: entry.subheadline
  } %}

  <section class="m_gallery position-relative">
    <div class="container">
      <div class="row gallery-items"></div>
      <div class="row text-center">
        {{ craft.craftAjaxinate.loadMoreVariable() }}
      </div>
    </div>
  </section>

  {{ craft.craftAjaxinate.render({
    template: 'gallery/_items',
    initLoad: true,
    containerClass: '.gallery-items',
    section: 'galleryItems',
    offset: 4,
    query:{
      'orderBy':'dateCreated asc',
    },
    })
  }};

  

{% endblock %}
```

and the code for gallery/_items:

```{% for item in entries %}
  <div class="col-md-6 col-lg-4">
    {% set thumb = item.galleryImages.one() %}                
    <img class="mb-3" src="{{ thumb.getUrl('galleryThumbnail') }}" width="{{ thumb.getWidth('galleryThumbnail') }}" height="{{ thumb.getHeight('galleryThumbnail') }}">
    <p class="font-weight-bold mb-0 text-uppercase">{{item.title}}</p>
    <p class="text-gray font-weight-bold mb-0">{{item.galleryLocationName}}</p>
  </div>
{% end%}
```

and a screenshot of the dashboard with the Plugin settings:
<img width="726" alt="Screen Shot 2020-02-04 at 12 00 34 PM" src="https://user-images.githubusercontent.com/6062181/73767817-f65fa400-4745-11ea-8306-5fa3b466a71c.png">

Can anyone help me find where I went wrong?

**Comment by ryanjohnsonnc** [comment]
A quick follow up here...
If I edit my gallery/_items file and remove for loop iterating over the entries object with just a static "Hello World", the request is successful and the load more functionality loads the proper number of "pages" with "Hello World". 
It appears something is going awry when exposing the entries object to the right template. I just can't figure out why or where at this point.

**Comment by insaurabh** [comment]
Hello @ryanjohnsonnc,

In your `gallery/_items` you have access to  `entries` object. All the ajax data will be available in this.

For example.

```twig

{% for item in entries %}
  <a href="{{item.url}}">{{ item.title }}</a>
  <span>Location : {{ item.galleryLocationName }} </span>
  .....
{% endfor %}
```

Let me know if you are still facing any issues.

**Comment by insaurabh** [comment]
There is no need to pass any settings in the back-end if you passed at the template level. As template have more preference over backend settings.

**Comment by ryanjohnsonnc** [comment]
Thank you @maddyBoy! Reading over your reply and looking back at my code helped me identify my issue.
