### ISSUE TITLE
Loading Indicator

### ISSUE THREAD

**Issue by jasenmpeterson** [Hestabit/craft-ajaxinate#15]
Is there a means of showing a loading indicator?

**Comment by insaurabh** [comment]
Hello @jasenmpeterson  ,

There is a default loader which you can even override by your custom template in `loaderTemplate`.

Let me know if you are still facing any issues.

**Comment by jasenmpeterson** [comment]
Ah, I guess I'm not seeing the loader because it happens so quickly. Thank you.
