### ISSUE TITLE
Custom Queries

### ISSUE THREAD

**Issue by jasenmpeterson** [Hestabit/craft-ajaxinate#16]
I'll be using this plugin in a multisite setup. The secondary site will share some filters/categories with the main site except for 'company categories'. I want to add a custom query that basically says 'find these entries based on this set of filter options/categories, but only ones that are also tagged with this specific company category'. How would I go about doing that?

I can can try to make this more clear if necessary. Thank you in advance.

**Comment by insaurabh** [comment]
Hi @jasenmpeterson 

You have option to pass the custom `query`. 

Just for reference

```twig
  {{ craft.craftAjaxinate.render({
      limit: 5,
      resetBtnState: 1,
      query:{
        'postDate': ['and', '>= 2019-07-12', '<= 2019-07-31'],
        'orWhere': ['and', ['=','field_featuredEntry',1]],
      }      
    }) }}
```

You can pass these combinations [Element Queries](https://docs.craftcms.com/v3/dev/element-queries/#executing-element-queries)


Let me know if you are still facing any issues.

**Comment by jasenmpeterson** [comment]
Thanks, I think I understand. I'll circle back if I'm wrong.
