### ISSUE TITLE
MultiSite

### ISSUE THREAD

**Issue by jasenmpeterson** [Hestabit/craft-ajaxinate#17]
Is there anything I should be on the look out for when using this plugin in a multisite setup? I'm currently getting this error: 'http://bcs.tellepsen-dev.ell-dev.com/actions/craft-ajaxinate/default/plugin-init 500 (Internal Server Error)'.

For context, the entries I'm attempting to retrieve are available to this secondary site. I'm not quite sure what I'm missing.

Also to clarify, the plugin works as it should on the 'main' site.

**Comment by insaurabh** [comment]
Hello @jasenmpeterson 

Can you please share the code that you're using while initializing the plugin instance.

![image](https://user-images.githubusercontent.com/26545067/87665266-46767400-c784-11ea-8f89-817af2d711ba.png)

**Comment by jasenmpeterson** [comment]
Here you go. 'building_concrete_solutions' is the handle for the secondary site. Not shown is the csrf token object.

<img width="502" alt="Screen Shot 2020-07-16 at 6 37 55 AM" src="https://user-images.githubusercontent.com/22401956/87666825-ef927f80-c72e-11ea-9963-fb23568d6cfe.png">

**Comment by jasenmpeterson** [comment]
Any word on this? I spent yesterday messing around with it and I’m at loss as to what to do. I’m guessing the plug-in is supposed to support multi site?

**Comment by jasenmpeterson** [comment]
A follow up on this, I figured it out. For some reason it didn't work without defining the template in the Plugin CP. Which is strange because it's not defined for the 'main' site. It is defined, but it's defined in the render function.

**Comment by jasenmpeterson** [comment]
Also, with that being said. I need the entries that are pulled in to be using the secondary sites URL. Not the primary sites. Is that possible?

**Comment by jasenmpeterson** [comment]
One last thing, how would I structure a custom query to find only entries that are related to a specific category?

query: {
'relatedTo': craft.categories.slug('bullding-concrete-solutions')
}

Isn't working so obviously it's wrong.

**Comment by insaurabh** [comment]
Hi @jasenmpeterson 

Sorry for the late response.

I need to test the way you are trying to pass the params in the `query` tag.

As in the core of this plugin. It works like

```yii
  $entryQuery = Entry::find(); // initiate the base query
```
apply other conditions and then append the `query` params as `key-value` pair like

```yii
  foreach ($query as $key => $value) {
    $entryQuery->$key($value);
 }
```

finally
```yii
 $entries = $entryQuery->all();
```
So you have to build your query in that way.

Hope it helps you to solve the problem.

**Comment by jasenmpeterson** [comment]
What I'm struggling with is the following scenario:

Some of my entires have multiple categories but from what I can tell the filter only works with the last category assigned, it's not accounting for the other categories. So if an entry that is assigned CatA and CatB the result will only return said entry if I select 'CatB" as a filter but it will not if I select 'CatA' and 'CatB" or just 'CatA'. To add to that there is an additional set of categories to further narrow down the results. That additional set of categories is separate from the 'default' categories. To get a visual of what I mean you can visit the following page: http://tellepsen-dev.ell-dev.com/expertise
