### ISSUE TITLE
step-by-step instruction

### ISSUE THREAD

**Issue by userbott** [Hestabit/craft-ajaxinate#2]
If it does not complicate, please make step by step instructions, perhaps with screenshots and code inserts. Example: Create a file in it, add in this place the code as in the example in the screenshot. Next in another file, add this code. In the admin, specify these settings. **Thank you in advance.**

**Comment by insaurabh** [comment]
Hi @userbott ,


- [ ] Did you created a template in the template folder of your project
- [ ]  Did you selected that template in plugin setting page.

- [ ]  Please include error messages and Screenshots of plugin setting page.

Thank You.
