### ISSUE TITLE
Fix Composer 2 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [Hestabit/craft-ajaxinate#20]
When installing this plugin with Composer 1, the following deprecation notice is output:

> Deprecation Notice: Class `hestabit\craftajaxinate\assetbundles\CraftAjaxinate\CraftAjaxinateAsset` located in `./vendor/hestabit/craft-ajaxinate/src/assetbundles/craftajaxinate/CraftAjaxinateAsset.php` does not comply with psr-4 autoloading standard\. It will not autoload anymore in Composer v2\.0\.

Composer 2 was released on October 24, and is now the default version that will be installed, so it’s critical that this gets resolved ASAP, or people will start getting `Class not found` errors.

To fix, run the following command:

```bash
> git mv src/assetbundles/craftajaxinate src/assetbundles/CraftAjaxinate
```

Then commit your change and [tag a new release](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases).

_(Note that you must use the `git mv` command, as Git tends to not notice case-sensitive file renames otherwise.)_

**Comment by insaurabh** [comment]
Hi, @brandonkelly 

Thanks for the detailed information. I will resolve this issue ASAP.

**Comment by saxenapritesh** [comment]
Hello, @brandonkelly 

I have checked this on Composer version 1 and 2 and it is installed successfully on both version.
Can you please share the full scenario when the error Occurred.

**Comment by brandonkelly** [comment]
I did… if it’s not an issue anymore feel free to close & ignore.

**Comment by DevOps-Hestabit-1** [comment]
Issue is fixed now its working with composer 2.
