### ISSUE TITLE
Failed to instantiate component or class "hestabit\craftajaxinate\assetbundles\CraftAjaxinate\CraftAjaxinateAsset".

### ISSUE THREAD

**Issue by lucosius** [Hestabit/craft-ajaxinate#21]
Hello,

I'm getting this error when i place {{ craft.craftAjaxinate.loadMoreVariable() }}

```
Not instantiable – yii\di\NotInstantiableException
Failed to instantiate component or class "hestabit\craftajaxinate\assetbundles\CraftAjaxinate\CraftAjaxinateAsset".
↵
Caused by: ReflectionException
Class hestabit\craftajaxinate\assetbundles\CraftAjaxinate\CraftAjaxinateAsset does not exist
in /home/telefonai/testing.telefonai.eu/vendor/yiisoft/yii2/di/Container.php at line 508
```

What should I do in this situation?

**Comment by insaurabh** [comment]
Hello @lucosius ,

Which craft version you are currently using?

Thank You.

**Comment by insaurabh** [comment]
Hello @lucosius 

Any update on this? I checked on the current stable version i.e 3.7.21 and it's working as expected.

**Comment by Eventhisone** [comment]
I am running into the same issue, running `Craft Pro 3.7.30.1` with Craft Ajaxinate version `2.0.1`.

**Comment by insaurabh** [comment]
Hello @Eventhisone ,

We tested on craft 4 with updated requirements and changes. We rolled out a new version so please download the latest from the store. 

Thank You.
