### ISSUE TITLE
How to choose which categories are enabled for filters?

### ISSUE THREAD

**Issue by daltonrooney** [Hestabit/craft-ajaxinate#3]
Maybe I'm missing something on the back-end, but I am wondering if there is a way for the end-user to select which category group to filter by? For example, for entry section called "Cars", I have a category called "Make" and a category group called "Type". "Make" might be "Volvo", "Ford", etc. Type might be "Car","Truck", "Minivan", etc.

So I would like to be able to choose which category groups are displayed, and additionally I would need to filter by multiple category groups.

**Comment by insaurabh** [comment]
Hi @daltonrooney,

Currently, there is no option to select the  ` category group ` on the backend, but while calling the filter variable you have the option to pass the name of `category group handle`.

`{{ craft.craftAjaxinate.render({
 catGroup: 'CatGroupHandle'
}) }}`

Use this code and let me know if you're still facing any issue.

- [ ] Did you enable  `Activate category filter.`  from the backend.

![craft-ajaxinate-filter](https://user-images.githubusercontent.com/26545067/61433882-1b2f2e00-a952-11e9-9165-4de65ea12aae.png)

**Comment by daltonrooney** [comment]
Great, thanks for that information, I’ll give it a try. Any thoughts on being able to filter by multiple categories at the same time?

**Comment by daltonrooney** [comment]
Sorry, to clarify my previous question - I see that I can pass an array of category group handles in the render tag, but all of the categories are being displayed in a single checkbox group. I would like to be able to split each category group into its own set of inputs. 

For an example see [https://facetwp.com/demo/](this demo). Each input group is pulled from a different taxonomy.

I'm also wondering if it's possible to change the input type for selecting a category? For some categories, a select or radio group would be more appropriate.

**Comment by anshul321** [comment]
Hi @daltonrooney , we have released a new version of the plugin which allows the developer to manage the configuration of the plugin on the template level. The above-mentioned feature has been added to the plugin as well.
Kindly update the plugin and share your valuable feedback. 

Thanks & Regards
