### ISSUE TITLE
Feature request: support for multiple configurations

### ISSUE THREAD

**Issue by daltonrooney** [Hestabit/craft-ajaxinate#4]
In some cases, we would want multiple configurations for a single site. For example, on the blog, we would like to pull from the "posts" section, using a specific template. In the resource library, we would want to pull from the "resources" section, using a different template. When using the render tag I don't see a way to specify which section to use as a source and which template to use for results.

It would be great if the render tag could replicate all of the settings from the Control Panel, so I could use different configs for different sections.

**Comment by daltonrooney** [comment]
In #5, I mentioned overriding the default query in the render tag. It seems like it would be nice to be able to override the template as well. So an example might look like:

```
{{ craft.craftAjaxinate.render({
   'query': [
      'section':'events',
      'orderBy':'startDate asc',
      'startDate':'">" ~ date(now)|atom"
    ],
   'template': 'ajax/events.twig'
}) }} 
```

**Comment by anshul321** [comment]
Hi @daltonrooney , we have released a new version of the plugin which allows the developer to manage the configuration of the plugin on the template level. The above-mentioned feature has been added to the plugin as well.
Kindly update the plugin and share your valuable feedback. 

Thanks & Regards
