### ISSUE TITLE
Feature request: More advanced query options

### ISSUE THREAD

**Issue by daltonrooney** [Hestabit/craft-ajaxinate#5]
Sorry to bombard you with feature requests! I'm very interested in this plugin and see a lot of potential. However we have some advanced requirements that we'd need to meet in order to use it... and I suspect this would be useful for users as well.

In this case, we have additional query parameters that we need to pass to the "load more" request. For example, we have an events content type with a startDate field. We only want to show future events in the feed, not past events. So the query looks like this:

```{% set entries = craft.entries.section('events').startDate(">" ~ date(now)|atom ).orderBy('startDate asc').all() %}```

However when I add the Load More button, it's pulling all events, starting from the very beginning. 

Any chance of being able to add support for more advanced queries into the render tag?

**Comment by anshul321** [comment]
Hi, @daltonrooney Thank you for writing in.
Can you please elaborate on the suggestion a bit more so that we can work in the right direction.

**Comment by daltonrooney** [comment]
Hi @anshul321, thanks for the follow up. In the example above, how would I filter the entry query to only display entries with a start date greater than today?

In my thinking, you could pass additional arguments via the render tag (as I mentioned in issue #4) and override the default query. So for this example, maybe the render tag looks like this:

``` 
{{ craft.craftAjaxinate.render({
   'query': [
      'section':'events',
      'orderBy':'startDate asc',
      'startDate':'">" ~ date(now)|atom"
    ],
}) }} 
```

What are your thoughts?

**Comment by anshul321** [comment]
Hi @daltonrooney , we are actually planning to add this feature in the next release. We are currently planning to make the start date dynamic so that the admin can easily select the field from which he/she wants to fetch the start date.

Will let you know once we are about to release the new update.

Thanks :)

**Comment by daltonrooney** [comment]
@anshul321 Thanks for taking my feedback into consideration. Glad to see you are responsive and eager to improve the software! Just to be clear, I was not suggesting any kind of hard-coded setting option for date based queries. That was simply the closest example I had because I am working on a project with that requirement at the moment.

What I am truly asking for is the ability to modify queries inside the render tag. I mentioned this in #4 as well. In order for the plugin to be as useful as possible to the widest number of people, you have to assume the query requirements are dynamic on a per-site and per-section basis. To provide a couple more use cases to consider:

1. A section called "stories" has a lightswitch field called "featured". We only want to display entries where "featured" = true.

2. A section called "properties" has a numerical "price" field. We only want to display properties where price > 1000000, sorted by the price field from highest to lowest.

3. A section called "pages" has a "shortDescription" field. We only want to display pages where "shortDescription" is not empty.

As you can imagine, there's no way to code all of these scenarios into a settings page. More importantly, the way your settings page works now, there is no way to have more than one configuration. Having the ability to pass a query and a template to the render tag would be one way to support both of these features.

Here's how I imagine each of these scenarios would look in the render tag:

1.
```
{{ craft.craftAjaxinate.render({
   'query': [
      'section':'stories',
      'featured':1
    ],
   'template': 'ajax/stories.twig',
}) }} 
```

2.
```
{{ craft.craftAjaxinate.render({
   'query': [
      'section':'properties',
      'orderBy': 'price desc',
      'price': '">=" ~ 1000000
    ],
   'template': 'ajax/properties.twig',
}) }} 
```

3.
```
{{ craft.craftAjaxinate.render({
   'query': [
      'section':'pages',
      'shortDescription':':notempty:'      
    ],
   'template': 'ajax/pages.twig',
}) }} 
```

**Comment by anshul321** [comment]
Hi @daltonrooney , we have released a new version of the plugin which allows the developer to manage the configuration of the plugin on the template level. The above-mentioned feature has been added to the plugin as well.
Kindly update the plugin and share your valuable feedback. 

Thanks & Regards
