### ISSUE TITLE
Scripts not loading on the front end

### ISSUE THREAD

**Issue by daltonrooney** [Hestabit/craft-ajaxinate#6]
When I first installed the plugin and set up my template, nothing was happening. I realized it was because no scripts were loaded on the front-end. I had to add the following tag to my template to get the scripts to load: 

```{% do view.registerAssetBundle("hestabit\\craftajaxinate\\assetbundles\\CraftAjaxinate\\CraftAjaxinateAsset") %}```

I would recommend adding this to the documentation if others are having the same problem.

**Comment by insaurabh** [comment]
Can you please check once that you called the `{{ craft.craftAjaxinate.loadMoreVariable() }}` for load more button as it registerAssetBundle for frontend.

Thank You.

**Comment by daltonrooney** [comment]
Thanks -- yes I can see now that I forgot to include the loadMoreVariable tag previously. Everything is working as it should.
